name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
  
    - name: Install Dependencies
      run: apt-get install -y cmake libpcap-dev libssl-dev

    - name: Build
      run: |
        mkdir build,
        cd build,
        cmake ..,
        make
